# Generated by Django 5.2.8 on 2025-12-01 06:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(db_index=True, max_length=64)),
                ('query_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prediction_score', models.FloatField(help_text='Model confidence (0.0 to 1.0)')),
                ('prediction_label', models.CharField(choices=[('FAKE', 'Fake'), ('REAL', 'Real')], max_length=10)),
                ('explainability_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='news',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='todaysnews',
            name='headlines',
            field=models.ManyToManyField(related_name='daily_features', to='Main.news'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Main_news_search__92cf3c_gin'),
        ),
    ]
